name: main

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  maven:
    uses: Harmelodic/github-workflows/.github/workflows/build-java-project.yaml@main
    with:
      maven_options: >
        --define skipPactPublish=true
