name: main

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24
      - run: >
          mvn install
          --no-transfer-progress
          --define skipPactPublish=true
